CREATE DATABASE Uganda;

USE Uganda;



CREATE TABLE DISTRICT  (
    DistrictCode VARCHAR(10) PRIMARY KEY NOT NULL,
    Name VARCHAR(15) UNIQUE,
    Region VARCHAR(15)
);

CREATE TABLE CITIZEN  (
    NIN BIGINT PRIMARY KEY NOT NULL,
    Fname VARCHAR(3) NOT NULL,
    LName VARCHAR(15) NOT NULL,
    Gender ENUM('Male','Female') NOT NULL,
    DistrictCode VARCHAR(10),
    FOREIGN KEY (DistrictCode) REFERENCES DISTRICT(DistrictCode)
)



ALTER TABLE CITIZEN MODIFY COLUMN Fname VARCHAR(15);



ALTER TABLE DISTRICT ADD COLUMN population INT;



INSERT INTO DISTRICT VALUES(1001,'Kampala','Central',4000000);
INSERT INTO DISTRICT VALUES(1002,'Lira','North',200000);
INSERT INTO CITIZEN VALUES(111111111111111,'Nathaniel','Mugenyi','Male',1002);
INSERT INTO CITIZEN VALUES(11111111111112,'Esther','Kica','Female',1001);


CREATE VIEW view1 AS SELECT COUNT (*) FROM DISTRICT;


CREATE VIEW view2 AS SELECT Fname, LName FROM CITIZEN;


CREATE VIEW view3 AS SELECT * FROM CITIZEN WHERE ;

CREATE VIEW view4 AS SELECT * FROM DISTRICT WHERE `Region`="North";

CREATE VIEW view5 AS SELECT COUNT (*) FROM CITIZEN;

CREATE VIEW view6 AS SELECT MAX(population) FROM DISTRICT;





